// Generated by CoffeeScript 2.4.1
(function() {
  var ffromPairs, flow, fmap, ruleNames, rules;

  ({
    flow,
    map: fmap,
    fromPairs: ffromPairs
  } = require('lodash/fp'));

  ruleNames = ['no-unnecessary-flowmax', 'needs-flowmax', 'prefer-flowmax', 'no-flowmax-in-forwardref', 'dependencies', 'require-adddisplayname'];

  rules = flow(function() {
    return ruleNames;
  }, fmap(function(ruleName) {
    return [ruleName, require(`./rules/${ruleName}`)];
  }), ffromPairs)();

  module.exports = {
    rules,
    configs: {
      recommended: {
        plugins: ['ad-hok'],
        parserOptions: {
          ecmaFeatures: {
            jsx: true
          }
        },
        rules: {
          'ad-hok/needs-flowmax': 'error',
          'ad-hok/prefer-flowmax': ['error', 'whenUsingUnknownHelpers'],
          'ad-hok/no-flowmax-in-forwardref': 'error'
        }
      }
    }
  };

}).call(this);
